# -*- coding: utf-8 -*-
"""
Created on Fri Jan 22 10:31:33 2021

@author: laury
"""

import smtplib

import os
import glob
import os.path, time
from datetime import datetime, timedelta


# import the corresponding modules
from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import base64

port = 2525
smtp_server = "smtp.mailtrap.io"
login = "d728ba75d68666" # paste your login generated by Mailtrap
password = "1ac13df426053f" # paste your password generated by Mailtrap

sender_email = "mailtrap@example.com"
receiver_email = "new@example.com"
message = MIMEMultipart()
message["Subject"] = "Daily Forecast Info"
message["From"] = sender_email
message["To"] = receiver_email


def get_csv():
    path = r'C:\Users\laury'
    extension = 'csv' 
    os.chdir(path)
    result = glob.glob('*.{}'.format(extension))
    for fil in result:
        last_mod = datetime.fromtimestamp(os.path.getmtime(fil))
        yesterday = datetime.now() - timedelta(days=1)
        if yesterday - last_mod >= timedelta(days=1):
            return (fil)

# Function which encodes&attaches a .csv file to the message; the filename is given by the function get_csv()
def place_attachement(filename):
    with open(filename, "rb") as attachment:
    # The content type "application/octet-stream" means that a MIME attachment is a binary file
      part1 = MIMEBase("application", "octet-stream")
      part1.set_payload(attachment.read())

       # Encode to base64
      encoders.encode_base64(part1)

       # Add header 
      part1.add_header(
      "Forecast file",
      f"attachment; filename= {filename}",
       )

    # Add attachment to your message and convert it to string
    return part1

message.attach(place_attachement(get_csv()))
    
encoded1 = base64.b64encode(open(r"C:\Users\laury\Desktop\assignments\PROG-DS\euclidian.png", "rb").read()).decode()
encoded2 = base64.b64encode(open(r"C:\Users\laury\Desktop\assignments\PROG-DS\manhattan.png", "rb").read()).decode()
encoded3 = base64.b64encode(open(r"C:\Users\laury\Desktop\assignments\PROG-DS\manhattan.png", "rb").read()).decode()

html = f"""\
<html>
 <body>
 <p>Hi,<br>
       Please find attached the daily forecast information</p>
    <h3>Image1</h3>  
   <img src="data:image/jpg;base64,{encoded1}" alt="Flowers in Chania" style="width:200px;height:200px;align = "top"; margin:10px 20px>
   <p>Image2</p>
   <img src="data:image/jpg;base64,{encoded2}" alt="bla" style="width:200px;height:200px;align = "middle"; margin:10px 100px">
   <p>Image3</p>
   <img src="data:image/jpg;base64,{encoded3}" alt="blable" style="width:200px;height:200px;align = "bottom"; margin:10px 20px">
   <p>Sincerely,<br>
       Laura</p>
 </body>
</html>
"""

part2 = MIMEText(html, "html")
message.attach(part2)

# send your email
with smtplib.SMTP("smtp.mailtrap.io", 2525) as server:
   server.login(login, password)
   server.sendmail(
       sender_email, receiver_email, message.as_string()
   )
print('Sent')